### ISSUE TITLE
Crash when not using ecmascript6

### ISSUE THREAD

**Issue by yuxal** [reframejs/reframe#33]
Tried to run with an older version of node, crashed on unexpected syntax on ecma6 features.

Need to use babel

**Comment by brillout** [comment]
Because of the eject commands I'd rather keep the code written with ES6.

Added code https://github.com/reframejs/reframe/commit/a20a98bd28e73fa338dd191cc833a1e2e2b0512e that tells the user to update her Node when she uses an unsupported Node version.

Let me know if you can't update your Node installation or if you have a reason not to.

**Comment by yuxal** [comment]
Already did, just thought it'd be nice to have.
